# mem
shared_buffers = 512MB
effective_cache_size = 1536MB
work_mem = 8MB
maintenance_work_mem = 384MB

# io
max_wal_size = 1536MB
wal_compression = on
synchronous_commit = off # success before disk write.
fsync = on
wal_writer_delay = 200ms # grp writes
checkpoint_timeout = 15min


# conns
max_connections = 200

# bgwriter
bgwriter_lru_maxpages = 100
bgwriter_delay = 200ms
bgwriter_flush_after = 512kB

# autovac
autovacuum_max_workers = 2
autovacuum_vacuum_cost_delay = 10ms
