arch: amd64
cores: 2
features: fuse=1,mknod=1,mount=nfs;cifs,nesting=1
hostname: lab-dev
memory: 4096
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=AA:11:22:BB:CC:33,ip=dhcp,type=veth
net1: name=eth1,bridge=vmbr1,firewall=1,gw=10.200.0.2,hwaddr=AA:11:22:BB:CC:33,ip=10.200.1.65/8,type=veth
ostype: centos
rootfs: local:105/vm-105-disk-0.raw,size=32G
swap: 0
